(function (root, factory) { const api = factory(); if (typeof module === 'object' && module.exports) module.exports = api; else root.WiFiDomain = api; })(typeof globalThis !== 'undefined' ? globalThis : this, function () {
    'use strict';
    const clone = v => JSON.parse(JSON.stringify(v));
    const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
    function permissions(u) { const active = u?.status === 'active', system = active && u.role === 'system_admin'; return { system, editSite: active && (system || u.role === 'site_admin'), users: active && (system || u.role === 'site_admin'), export: active && (system || !!u.canExport), report: active && (system || !!u.canGenerateReports) }; }
    function siteIds(u, sites) { return u?.status === 'active' ? sites.filter(s => permissions(u).system || u.siteIds.includes(s.id)).map(s => s.id) : []; }
    function canManageUser(actor, target, sites) { return permissions(actor).system || permissions(actor).users && ['site_admin', 'site_viewer'].includes(target.role) && target.siteIds.length > 0 && target.siteIds.every(id => siteIds(actor, sites).includes(id)); }
    function validateUser(actor, u, users, sites) { const issues = [], old = users.find(x => x.id === u.id); if (!canManageUser(actor, u, sites) || old && !canManageUser(actor, old, sites)) issues.push('ไม่มีสิทธิ์กำหนด Role หรือ Site ชุดนี้'); if (!/^[A-Za-z0-9._-]{3,40}$/.test(u.username)) issues.push('Username ต้องเป็น a-z, 0-9, . _ - จำนวน 3–40 ตัว'); if (users.some(x => x.id !== u.id && x.username.toLowerCase() === u.username.toLowerCase())) issues.push('Username ซ้ำ'); if (!permissions(actor).system && u.canExport && !old?.canExport && !permissions(actor).export) issues.push('ไม่มีสิทธิ์เพิ่ม Export'); if (!permissions(actor).system && u.canGenerateReports && !old?.canGenerateReports && !permissions(actor).report) issues.push('ไม่มีสิทธิ์เพิ่ม Gen Report'); if (!u.name.trim() || !validEmail(u.email)) issues.push('ชื่อหรือ Email ไม่ถูกต้อง'); if (!u.siteIds.length || u.siteIds.some(id => !sites.some(s => s.id === id))) issues.push('เลือก Site ที่ถูกต้อง'); if (!['system_admin', 'site_admin', 'site_viewer'].includes(u.role) || !['active', 'disabled'].includes(u.status)) issues.push('Role หรือ Status ไม่ถูกต้อง'); if (old?.role === 'system_admin' && old.status === 'active' && (u.role !== 'system_admin' || u.status !== 'active') && !users.some(x => x.id !== u.id && x.role === 'system_admin' && x.status === 'active')) issues.push('ต้องเหลือ System Admin ที่ Active อย่างน้อยหนึ่งบัญชี'); return issues; }
    function validDate(v) { if (!/^\d{4}-\d{2}-\d{2}$/.test(v || '')) return false; const d = new Date(v + 'T00:00:00Z'); return Number.isFinite(d.getTime()) && d.toISOString().slice(0, 10) === v; }
    function buildReport({ rows, types, sites, user, filter }) { if (!permissions(user).report) throw Error('ไม่มีสิทธิ์ Gen Report'); const allowed = siteIds(user, sites); if (filter.site !== 'all' && !allowed.includes(filter.site)) throw Error('ไม่มีสิทธิ์ใน Site นี้'); if (!validDate(filter.from) || !validDate(filter.to) || filter.from > filter.to) throw Error('ช่วงวันที่ไม่ถูกต้อง'); if (!Object.hasOwn(types, filter.type)) throw Error('ประเภทรายงานไม่ถูกต้อง'); const source = rows.filter(r => allowed.includes(r.site) && (filter.site === 'all' || r.site === filter.site) && r.date >= filter.from && r.date <= filter.to); const keys = ['success', 'reject', 'timeout', 'register', 'up', 'down', 'issued', 'used', 'attempts', 'totalTraffic', 'unused']; const totals = Object.fromEntries(keys.map(k => [k, source.reduce((n, r) => n + Number(r[k] || 0), 0)])); const groups = new Map(); for (const r of source) { const k = r.date + (filter.group === 'site' ? ':' + r.site : ''); if (!groups.has(k)) groups.set(k, { date: r.date, site: filter.group === 'site' ? r.site : 'all', ...Object.fromEntries(keys.map(k => [k, 0])) }); for (const key of keys) groups.get(k)[key] += Number(r[key] || 0); } return { filter: clone(filter), definition: clone(types[filter.type]), rows: [...groups.values()].sort((a, b) => (a.date + a.site).localeCompare(b.date + b.site)), totals, sourceCount: source.length, siteIds: [...new Set(source.map(r => r.site))], createdAt: new Date().toISOString() }; }
    function csv(report, sites) { const cell = v => '"' + String(v ?? '').replace(/^\s*[=+@-]/, "'$&").replace(/"/g, '""') + '"'; return '\ufeff' + [['Wi-Fi Tools · ข้อมูลตัวอย่าง'], ['วันที่', 'Site', ...report.definition.columns.map(c => c[1])], ...report.rows.map(r => [r.date, r.site === 'all' ? 'รวม Site ตามสิทธิ์' : sites.find(s => s.id === r.site)?.name || r.site, ...report.definition.columns.map(c => r[c[0]])])].map(row => row.map(cell).join(',')).join('\r\n'); }
    function validEmail(v) { return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v); }
    function parseEmails(v) { const list = [...new Set(v.split(/[;,\n]/).map(x => x.trim()).filter(Boolean))]; if (!list.length || list.some(x => !validEmail(x))) throw Error('Email ไม่ถูกต้อง ใช้ comma คั่นผู้รับหลายคน'); return list; }
    function nextMonthlyRun(day, time, now = new Date()) { if (!Number.isInteger(day) || day < 1 || day > 28 || !/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(time)) throw Error('กำหนดวัน 1–28 และเวลาให้ถูกต้อง'); const b = new Date(now.getTime() + 7 * 3600000), [h, m] = time.split(':').map(Number); let due = new Date(Date.UTC(b.getUTCFullYear(), b.getUTCMonth(), day, h - 7, m)); if (due <= now) due = new Date(Date.UTC(b.getUTCFullYear(), b.getUTCMonth() + 1, day, h - 7, m)); const l = new Date(due.getTime() + 7 * 3600000); return { due: due.toISOString(), from: new Date(Date.UTC(l.getUTCFullYear(), l.getUTCMonth() - 1, 1)).toISOString().slice(0, 10), to: new Date(Date.UTC(l.getUTCFullYear(), l.getUTCMonth(), 0)).toISOString().slice(0, 10) }; }
    return { clone, esc, permissions, siteIds, canManageUser, validateUser, validDate, buildReport, csv, parseEmails, nextMonthlyRun };
});
