/* Generated from data/*.json. Do not edit this file by hand. */
window.NT_DATA = {
  "config": {
    "format": "nt-wifi-offline-config",
    "schemaVersion": 1,
    "version": 1,
    "state": {
      "name": "NT Free WiFi",
      "template": "NT-Template01",
      "site": "Demo Site / NT-Free-WiFi",
      "path": "/portal/demo",
      "buttonColor": "#086cf0",
      "buttonTextColor": "#ffffff",
      "shape": "rounded",
      "guest": true,
      "member": false,
      "otp": false,
      "line": false,
      "google": false,
      "facebook": false,
      "apple": false,
      "smsProvider": "",
      "otpTtl": 180,
      "otpResend": 60,
      "otpAttempts": 5,
      "termsEnabled": true,
      "termsVersion": "draft-1",
      "termsTh": "ยอมรับเงื่อนไขการใช้งาน Free WiFi",
      "termsEn": "I accept the Free WiFi terms of use",
      "surveyEnabled": false,
      "surveyType": "survey",
      "question": "คุณใช้ WiFi เพื่อทำกิจกรรมใดเป็นหลัก?",
      "answers": "ทำงาน,เรียน,ติดต่อสื่อสาร",
      "correctAnswer": "ทำงาน",
      "videoEnabled": false,
      "videoSeconds": 15,
      "policyName": "Free WiFi Default",
      "downloadMbps": 20,
      "uploadMbps": 10,
      "hours": 1,
      "quotaGb": 0,
      "concurrent": 1,
      "allowedSite": "Demo Site",
      "vendor": "MikroTik",
      "model": "",
      "firmware": "",
      "controllerMode": "Controller",
      "voucherMode": "click",
      "repeatPolicy": "1 ครั้งต่ออุปกรณ์ต่อวัน",
      "alertEvent": "RADIUS Timeout",
      "alertThreshold": 5,
      "alertWindow": 5,
      "alertChannel": "In-app",
      "alertRecovery": true
    },
    "copy": {
      "th": {
        "title": "Free WiFi",
        "subtitle": "เชื่อมต่ออินเทอร์เน็ตฟรี สำหรับทุกคน",
        "button": "รับสิทธิ์ใช้งานฟรี",
        "otp": "รับรหัส OTP",
        "error": "ไม่สามารถเข้าสู่ระบบได้ กรุณาลองอีกครั้ง"
      },
      "en": {
        "title": "Free WiFi",
        "subtitle": "Stay connected, wherever you are.",
        "button": "Get free WiFi",
        "otp": "Request OTP",
        "error": "Unable to connect. Please try again."
      }
    },
    "assets": {
      "logo": "",
      "banner": "",
      "background": ""
    },
    "lists": {
      "wg": [],
      "mac": []
    }
  },
  "dashboard": {
    "sites": [
      {
        "id": "a",
        "name": "Demo Site A",
        "active": 124,
        "online": 12,
        "aps": 12,
        "success": 640,
        "attempts": 660,
        "traffic": 86.4,
        "issued": 80,
        "used": 58,
        "alerts": 0,
        "methods": [
          340,
          200,
          70,
          30
        ],
        "trend": [
          12,
          8,
          18,
          64,
          108,
          96,
          138,
          124
        ]
      },
      {
        "id": "b",
        "name": "Demo Site B",
        "active": 78,
        "online": 9,
        "aps": 10,
        "success": 420,
        "attempts": 440,
        "traffic": 52.8,
        "issued": 60,
        "used": 42,
        "alerts": 2,
        "methods": [
          220,
          130,
          55,
          15
        ],
        "trend": [
          6,
          4,
          9,
          40,
          72,
          58,
          86,
          78
        ]
      },
      {
        "id": "c",
        "name": "Demo Site C",
        "active": 46,
        "online": 7,
        "aps": 8,
        "success": 290,
        "attempts": 300,
        "traffic": 28.8,
        "issued": 40,
        "used": 26,
        "alerts": 1,
        "methods": [
          150,
          80,
          45,
          15
        ],
        "trend": [
          3,
          2,
          5,
          22,
          38,
          32,
          54,
          46
        ]
      }
    ],
    "incidents": [
      {
        "site": "b",
        "time": "20:54",
        "title": "AP-B10 Offline",
        "detail": "ตัวอย่าง: ไม่พบ Heartbeat จาก Controller ต้องตรวจไฟเลี้ยงและ Uplink",
        "level": "ต้องตรวจสอบ"
      },
      {
        "site": "b",
        "time": "20:48",
        "title": "RADIUS Timeout เพิ่มขึ้น",
        "detail": "ตัวอย่าง: ตรวจเส้นทางระหว่าง NAS และ RADIUS ก่อนสรุปสาเหตุ",
        "level": "เฝ้าระวัง"
      },
      {
        "site": "c",
        "time": "20:41",
        "title": "AP-C08 Offline",
        "detail": "ตัวอย่าง: Controller รายงาน Offline รอยืนยันสาเหตุจากหน้างาน",
        "level": "ต้องตรวจสอบ"
      }
    ],
    "snapshot": "2026-09-17T21:00:00+07:00",
    "times": [
      "00",
      "03",
      "06",
      "09",
      "12",
      "15",
      "18",
      "21"
    ],
    "methods": [
      "Free WiFi / คูปอง",
      "SMS / OTP",
      "Username / Password",
      "Social Login"
    ]
  },
  "reports": {
    "rows": [
      {
        "date": "2026-09-15",
        "site": "a",
        "success": 554,
        "reject": 12,
        "timeout": 4,
        "register": 74,
        "up": 13.1,
        "down": 57,
        "issued": 70,
        "used": 49,
        "attempts": 570,
        "totalTraffic": 70.1,
        "unused": 21
      },
      {
        "date": "2026-09-15",
        "site": "b",
        "success": 352,
        "reject": 15,
        "timeout": 5,
        "register": 48,
        "up": 8.3,
        "down": 35.2,
        "issued": 50,
        "used": 35,
        "attempts": 372,
        "totalTraffic": 43.5,
        "unused": 15
      },
      {
        "date": "2026-09-15",
        "site": "c",
        "success": 245,
        "reject": 7,
        "timeout": 3,
        "register": 30,
        "up": 4.5,
        "down": 18.2,
        "issued": 30,
        "used": 22,
        "attempts": 255,
        "totalTraffic": 22.7,
        "unused": 8
      },
      {
        "date": "2026-09-16",
        "site": "a",
        "success": 602,
        "reject": 14,
        "timeout": 4,
        "register": 79,
        "up": 14.8,
        "down": 64.1,
        "issued": 75,
        "used": 54,
        "attempts": 620,
        "totalTraffic": 78.89999999999999,
        "unused": 21
      },
      {
        "date": "2026-09-16",
        "site": "b",
        "success": 394,
        "reject": 13,
        "timeout": 3,
        "register": 52,
        "up": 9.1,
        "down": 39.7,
        "issued": 55,
        "used": 39,
        "attempts": 410,
        "totalTraffic": 48.800000000000004,
        "unused": 16
      },
      {
        "date": "2026-09-16",
        "site": "c",
        "success": 270,
        "reject": 9,
        "timeout": 3,
        "register": 34,
        "up": 5.1,
        "down": 21.5,
        "issued": 35,
        "used": 25,
        "attempts": 282,
        "totalTraffic": 26.6,
        "unused": 10
      },
      {
        "date": "2026-09-17",
        "site": "a",
        "success": 640,
        "reject": 16,
        "timeout": 4,
        "register": 85,
        "up": 16.4,
        "down": 70,
        "issued": 80,
        "used": 58,
        "attempts": 660,
        "totalTraffic": 86.4,
        "unused": 22
      },
      {
        "date": "2026-09-17",
        "site": "b",
        "success": 420,
        "reject": 14,
        "timeout": 6,
        "register": 56,
        "up": 9.8,
        "down": 43,
        "issued": 60,
        "used": 42,
        "attempts": 440,
        "totalTraffic": 52.8,
        "unused": 18
      },
      {
        "date": "2026-09-17",
        "site": "c",
        "success": 290,
        "reject": 8,
        "timeout": 2,
        "register": 38,
        "up": 5.8,
        "down": 23,
        "issued": 40,
        "used": 26,
        "attempts": 300,
        "totalTraffic": 28.8,
        "unused": 14
      }
    ],
    "types": {
      "login": {
        "name": "Login / Register",
        "columns": [
          [
            "success",
            "Login สำเร็จ"
          ],
          [
            "register",
            "สมัครใหม่"
          ],
          [
            "attempts",
            "Auth ทั้งหมด"
          ]
        ],
        "measure": "success",
        "chart": "Login สำเร็จรายวัน",
        "unit": "ครั้ง",
        "definition": "Login นับเหตุการณ์สำเร็จ ไม่ใช่บุคคลไม่ซ้ำ · สมัครใหม่แยกนับจากเหตุการณ์ Login"
      },
      "auth": {
        "name": "Authentication",
        "columns": [
          [
            "attempts",
            "คำขอทั้งหมด"
          ],
          [
            "success",
            "Accept"
          ],
          [
            "reject",
            "Reject"
          ],
          [
            "timeout",
            "Timeout"
          ]
        ],
        "measure": "attempts",
        "chart": "Authentication Requests รายวัน",
        "unit": "ครั้ง",
        "definition": "คำขอทั้งหมด = Accept + Reject + Timeout ในชุดข้อมูลตัวอย่างนี้"
      },
      "traffic": {
        "name": "Traffic Usage",
        "columns": [
          [
            "up",
            "Upload (GB)"
          ],
          [
            "down",
            "Download (GB)"
          ],
          [
            "totalTraffic",
            "รวม (GB)"
          ]
        ],
        "measure": "totalTraffic",
        "chart": "Data Usage รายวัน",
        "unit": "GB",
        "definition": "ปริมาณข้อมูล Upload + Download สะสมตามช่วงเวลา ไม่ใช่ความเร็วอินเทอร์เน็ต · หน่วย GB"
      },
      "coupon": {
        "name": "Free WiFi Coupon",
        "columns": [
          [
            "issued",
            "ออกคูปอง"
          ],
          [
            "used",
            "ใช้แล้ว"
          ],
          [
            "unused",
            "ยังไม่ใช้"
          ]
        ],
        "measure": "issued",
        "chart": "คูปองที่ออกแต่ละวัน",
        "unit": "ใบ",
        "definition": "จัดกลุ่มคูปองตามวันที่ออก · ใช้แล้วคือสถานะ ณ Snapshot · ชุดตัวอย่างนี้ไม่มีคูปองหมดอายุหรือเพิกถอน"
      }
    },
    "dateFrom": "2026-09-15",
    "dateTo": "2026-09-17",
    "timezone": "Asia/Bangkok",
    "snapshot": "2026-09-17T21:00:00+07:00"
  },
  "logs": [
    {
      "type": "portal",
      "id": "DEMO-001",
      "title": "GET /portal/demo → HTTP 200",
      "detail": "แสดงหน้า Portal สำเร็จ · ตัวอย่าง"
    },
    {
      "type": "auth",
      "id": "DEMO-002",
      "title": "RADIUS Timeout",
      "detail": "ยังไม่พบคำตอบจาก RADIUS · ต้องตรวจปลายทางและเส้นทางเครือข่ายก่อนสรุปสาเหตุ"
    },
    {
      "type": "accounting",
      "id": "DEMO-003",
      "title": "Interim-Update",
      "detail": "ตัวอย่างข้อมูล Session จาก NAS · ไม่ใช่สถานะออนไลน์จริง"
    },
    {
      "type": "audit",
      "id": "DEMO-004",
      "title": "Portal Draft updated",
      "detail": "ตัวอย่างประวัติการเปลี่ยน Config โดยผู้ดูแล"
    }
  ],
  "modules": [
    [
      "ThaiD / Email / AD-LDAP",
      "ออกแบบ Connector ตามข้อมูลและสิทธิ์ที่ผู้ให้บริการอนุญาต",
      "รอ Integration"
    ],
    [
      "Reports & Export",
      "Login / Register, Traffic, Peak Time, Quiz, Video และ Top Clients · PDF / XLSX / CSV / PPTX",
      "แผนพัฒนา"
    ],
    [
      "AI Reports & Dashboard",
      "เลือกข้อมูล สร้างมุมมอง และสรุปพร้อมช่วงเวลาและแหล่งอ้างอิง",
      "แผนพัฒนา"
    ],
    [
      "AI Config & Troubleshooting",
      "เสนอ Policy / AP Config และวิเคราะห์ Log พร้อมหลักฐาน · ตรวจผลก่อน Apply",
      "แผนพัฒนา"
    ],
    [
      "Multi-site / Tenant / RBAC",
      "แยกสิทธิ์องค์กร Site Admin, NOC, Front Desk และผู้ดูรายงาน",
      "แผนพัฒนา"
    ],
    [
      "Payment & Billing",
      "QR / Payment Gateway, Transaction reconciliation และสิทธิ์หลังชำระเงิน",
      "ขอบเขตต่อยอด"
    ],
    [
      "Backup / Restore / HA",
      "สำรอง Config และข้อมูล ทดสอบกู้คืน และกำหนด RPO / RTO",
      "แผนพัฒนา"
    ],
    [
      "Heatmap / RF / Traffic Analysis",
      "ต้องมี Telemetry และตำแหน่งอุปกรณ์ · RADIUS เพียงอย่างเดียวให้ข้อมูลไม่ครบ",
      "รอแหล่งข้อมูล"
    ],
    [
      "Audit & Privacy",
      "ประวัติการแก้ไข Version ของ Terms, Consent แยกวัตถุประสงค์ และอายุ Log",
      "แผนพัฒนา"
    ]
  ],
  "navigation": [
    {
      "id": "dashboard",
      "file": "dashboard.html",
      "title": "Dashboard",
      "subtitle": "ภาพรวมการให้บริการ NT WiFi · Sessions, AP, Authentication และเหตุการณ์"
    },
    {
      "id": "builder",
      "file": "portal-config.html",
      "title": "Portal Configuration",
      "subtitle": "ตั้งค่าหน้า Free WiFi และดูตัวอย่างขณะปรับค่า"
    },
    {
      "id": "reports",
      "file": "reports.html",
      "title": "Reports",
      "subtitle": "รายงานการใช้งาน NT WiFi · เลือก Site ช่วงวันที่ และประเภทข้อมูล"
    },
    {
      "id": "radius",
      "file": "radius-policy.html",
      "title": "RADIUS & Policy",
      "subtitle": "กำหนดสิทธิ์การใช้งานจากนโยบายกลาง"
    },
    {
      "id": "access",
      "file": "ap-network.html",
      "title": "AP & Network",
      "subtitle": "เชื่อมต่ออุปกรณ์และจัดการข้อยกเว้นเครือข่าย"
    },
    {
      "id": "voucher",
      "file": "free-wifi-coupons.html",
      "title": "Free WiFi & Coupon",
      "subtitle": "รับสิทธิ์ฟรีเป็นรายชั่วโมง พร้อมเงื่อนไขการใช้งาน"
    },
    {
      "id": "monitor",
      "file": "monitor-logs.html",
      "title": "Monitor & Logs",
      "subtitle": "ตรวจสถานะและติดตามเหตุการณ์จากต้นทางถึงปลายทาง"
    },
    {
      "id": "alerts",
      "file": "alerts.html",
      "title": "การแจ้งเตือน",
      "subtitle": "กำหนดเหตุการณ์ ช่องทาง และการแจ้งกลับเมื่อระบบฟื้นตัว"
    },
    {
      "id": "modules",
      "file": "modules.html",
      "title": "โมดูลตามสเปก",
      "subtitle": "รายการเพิ่มเติมที่ใช้ประกอบการพัฒนาระบบ"
    }
  ]
};
