(function () {
    'use strict'; if (!window.NT) return; const { q, qa, esc, db, can, siteName, persist } = NT, D = WiFiDomain;
    if (!can('users')) { q('#page-content').textContent = 'ไม่มีสิทธิ์จัดการผู้ใช้'; return; }
    q('#role-cards').innerHTML = NT_DATA.roles.map(r => '<div class="wt-card"><strong>' + esc(r.name) + '</strong><p>' + esc(r.description) + '</p></div>').join('');
    q('#user-role').innerHTML = NT_DATA.roles.filter(r => can('system') || r.id !== 'system_admin').map(r => '<option value="' + r.id + '">' + esc(r.name) + '</option>').join('');
    q('#user-sites').innerHTML = NT.allowedSites().map(s => '<label><input type="checkbox" data-user-site value="' + s.id + '">' + esc(s.name) + '</label>').join('');
    function role() { const all = q('#user-role').value === 'system_admin'; qa('[data-user-site]').forEach(e => { e.disabled = all; if (all) e.checked = true; }); for (const s of ['#user-export', '#user-report']) { q(s).disabled = all; if (all) q(s).checked = true; } }
    function edit(id) { const u = db.users.find(u => u.id === id); if (u && !D.canManageUser(NT.getUser(), u, NT_DATA.sites)) return; q('#user-form').reset(); q('#user-id').value = u?.id || ''; for (const k of ['username', 'name', 'email']) q('#user-' + k).value = u?.[k] || ''; q('#user-role').value = u?.role || 'site_viewer'; q('#user-status').value = u?.status || 'active'; q('#user-export').checked = !!u?.canExport; q('#user-report').checked = !!u?.canGenerateReports; qa('[data-user-site]').forEach(e => e.checked = u ? u.siteIds.includes(e.value) : e.value === NT.currentSite); role(); }
    function render() { const scope = NT.allowedIds(); q('#users-table').innerHTML = db.users.filter(u => can('system') || u.role !== 'system_admin' && u.siteIds.some(s => scope.includes(s))).map(u => '<tr><td>' + esc(u.username) + '<br>' + esc(u.name) + '</td><td>' + esc(u.role) + '</td><td>' + esc(u.siteIds.filter(s => scope.includes(s)).map(siteName).join(', ')) + '</td><td>' + (D.permissions(u).export ? 'ได้' : 'ไม่ได้') + '</td><td>' + (D.permissions(u).report ? 'ได้' : 'ไม่ได้') + '</td><td>' + esc(u.status) + '</td><td><button class="nt-button" data-edit-user="' + esc(u.id) + '" ' + (D.canManageUser(NT.getUser(), u, NT_DATA.sites) ? '' : 'disabled') + '>แก้ไข</button></td></tr>').join(''); qa('[data-edit-user]').forEach(e => e.addEventListener('click', () => edit(e.dataset.editUser))); }
    q('#user-new').addEventListener('click', () => edit(null)); q('#user-role').addEventListener('change', role);
    q('#user-form').addEventListener('submit', e => { e.preventDefault(); const u = { id: q('#user-id').value || 'u-' + Date.now(), username: q('#user-username').value.trim(), name: q('#user-name').value.trim(), email: q('#user-email').value.trim(), role: q('#user-role').value, status: q('#user-status').value, siteIds: qa('[data-user-site]').filter(e => e.checked).map(e => e.value), canExport: q('#user-export').checked, canGenerateReports: q('#user-report').checked }; if (u.role === 'system_admin') { u.siteIds = NT_DATA.sites.map(s => s.id); u.canExport = true; u.canGenerateReports = true; } const errors = D.validateUser(NT.getUser(), u, db.users, NT_DATA.sites); if (errors.length) { q('#user-message').textContent = errors.join(' · '); return; } const i = db.users.findIndex(x => x.id === u.id); if (i < 0) db.users.push(u); else db.users[i] = u; persist(); render(); q('#user-message').textContent = 'บันทึกผู้ใช้และสิทธิ์ในต้นแบบแล้ว'; if (u.id === NT.user.id) location.reload(); }); render(); edit(null);
})();
